import type { StarterLesson } from './starter-courses'

// All teaching, checks and sentences below are original. Publisher links are
// reference entry points, not transcript attribution or validated sound assets.
const alphabetSource = 'https://learningenglish.voanews.com/a/lets-learn-english-lesson-one/3111026.html'
const helpSource = 'https://learningenglish.voanews.com/a/lets-learn-english-lesson-3-i-am-here/3126527.html'
const directionsSource = 'https://learningenglish.voanews.com/a/lets-learn-english-lesson-10/3285228.html'
type Foundation = NonNullable<StarterLesson['foundation']>
type Context = readonly [key: string, promptZh: string, reference: string, meaningZh: string, explanationZh: string, alternatives: readonly string[]]
type ErrorExample = readonly [input: string, feedbackZh: string]
type Seed = {
  position: number; titleZh: string; goalZh: string; text: string; meaningZh: string; explanationZh: string
  pieces: string[]; recognitionZh: string; distractorZh: string; expressionZh: string
  alternatives: string[]; errors: ErrorExample[]; contexts: Context[]; sourceUrl?: string
}

function foundation(titleZh: string, explanationZh: string, examples: Foundation['examples'], promptZh: string,
  correct: string, contrast: string): Foundation {
  return { titleZh, explanationZh, examples, sourceUrl: alphabetSource,
    sourceInstructionZh: '打开 VOA 官方首课，在 Learn the alphabet 入口寻找真人字母参考；也可听页面真人对话。这里的拼读例词和讲解是本站原创，不保证原站有逐词对照录音。没有声音或不会音标时先认字形，不凭勾选认定已听懂或发音正确；不必看完整视频，不用汉字谐音。',
    check: { promptZh, choices: [{ id: 'match', textZh: correct }, { id: 'contrast', textZh: contrast }], answerId: 'match',
      explanationZh: '按上面已教的字形、词形或标记核对即可。这是文字辨认，不是声音辨别、听力或发音评分。' } }
}

function letterGroup(letters: readonly (readonly [letter: string, name: string])[], contrast: string): Foundation {
  const labels = letters.map(([letter]) => letter).join('、')
  return foundation(`字母名与大小写：${labels}`,
    '先看一小组大写和小写，再去真人参考听字母名称。斜线里的音标只是读音提示，不会音标也能先认字形；不要把字母名称当成所有单词里的读音。名称相同的大小写可以写得不同，单词拼读后面另教；不要求先背完字母表才能说本课短句。',
    letters.map(([letter, name]) => ({ text: `${letter} ${letter.toLowerCase()} — ${name}`,
      meaningZh: `${letter} 和 ${letter.toLowerCase()} 是同一个字母的大小写；${name} 提示常见美式字母名称，不是已试听认证。` })),
    `按上面示范顺序，哪组是 ${labels} 的小写字形？`, `字形：${letters.map(([letter]) => letter.toLowerCase()).join(' / ')}`, `字形：${contrast}`)
}

const foundations: Foundation[] = [
  letterGroup([['A', '/eɪ/'], ['B', '/biː/'], ['C', '/siː/'], ['D', '/diː/']], 'a / b / c / o'),
  letterGroup([['E', '/iː/'], ['F', '/ɛf/'], ['G', '/dʒiː/'], ['H', '/eɪtʃ/']], 'e / f / g / n'),
  letterGroup([['I', '/aɪ/'], ['J', '/dʒeɪ/'], ['K', '/keɪ/'], ['L', '/ɛl/']], 'i / j / k / t'),
  letterGroup([['M', '/ɛm/'], ['N', '/ɛn/'], ['O', '/oʊ/'], ['P', '/piː/']], 'm / n / o / q'),
  letterGroup([['Q', '/kjuː/'], ['R', '/ɑr/'], ['S', '/ɛs/'], ['T', '/tiː/'], ['U', '/juː/']], 'q / r / s / t / v'),
  letterGroup([['V', '/viː/'], ['W', '/ˈdʌbəljuː/'], ['X', '/ɛks/'], ['Y', '/waɪ/'], ['Z', '/ziː/']], 'v / w / x / y / s'),
  foundation('字母名不是单词音：短 a、短 i',
    'A 的名称常写作 /eɪ/，但 cat 里的 a 常为 /æ/；I 的名称 /aɪ/ 不等于 sit 里的短 /ɪ/。先把例词和意思配起来。音标不必先背，不用中文谐音；这些只是常见对应，有例外，也不能据文字判断你是否听出了区别。',
    [{ text: 'cat', meaningZh: '猫；这里的 a 是常见短元音 /æ/。' }, { text: 'sit', meaningZh: '坐；这里的 i 是常见短元音 /ɪ/。' }],
    '按上面的例词，哪组分别表示“猫”和“坐”？', '词形：cat / sit', '词形：sit / cat'),
  foundation('补上短 e、短 o、短 u',
    'bed 中 e 常为 /ɛ/，美式 hot 中 o 常为 /ɑ/，cup 中 u 常为 /ʌ/，都不能直接用字母名替代。地域和单词会有差异；先认识这三个例词，不把一个规则套给每个拼写。听不到参考时，检查只记文字辨认。',
    [{ text: 'bed', meaningZh: '床；短 e 的一个例词。' }, { text: 'hot', meaningZh: '热；常见美式短 o 的一个例词。' }, { text: 'cup', meaningZh: '杯子；短 u 的一个例词。' }],
    '哪组按上面顺序写出“床、热、杯子”？', '词形：bed / hot / cup', '词形：bad / hut / cap'),
  foundation('把一个短词拼起来：CVC',
    'C 表示辅音字母，V 表示元音字母。cat 可看成 c-a-t，sit 是 s-i-t；不是念三次字母名称。先在已教例词里找结构，不要求自己猜新词发音。CVC 是常见入门模式，并非所有三字母词都照这个规则读。',
    [{ text: 'c-a-t → cat', meaningZh: '三个字母合成“猫”这个词。' }, { text: 's-i-t → sit', meaningZh: '三个字母合成“坐”这个词。' }],
    '哪种拆分与上面的 cat 示范一致？', '拆分：c-a-t → cat', '拆分：c-t-a → cat'),
  foundation('末尾 e 常改变前面的元音',
    '比较 cap / cape、kit / kite：后一组末尾的 e 通常不单独发音，前面的元音常读接近字母名称。只是这类词的常见模式；have、give 就不能机械套用。先辨认有没有末尾 e，再去可靠参考听，不从拼写自动判发音。',
    [{ text: 'cap / cape', meaningZh: '帽子 / 披肩；第二个词多一个末尾 e。' }, { text: 'kit / kite', meaningZh: '成套工具 / 风筝；第二个词多一个末尾 e。' }, { text: 'have / give', meaningZh: '有 / 给；提醒你规则有例外。' }],
    '哪组是上面展示的“多了末尾 e”的词？', '词形：cape / kite', '词形：cap / kit'),
  foundation('两字母可以合成一个常见辅音：sh、ch',
    'ship 的 sh 常提示 /ʃ/，chip 的 ch 常提示 /tʃ/。不要拆成字母名 s-h 或 c-h 来读词；先看拼写和意思。ch 在 school 等词里有不同对应，不把今天的常见模式说成唯一读法。',
    [{ text: 'ship', meaningZh: '船；开头写 sh。' }, { text: 'chip', meaningZh: '小薄片或薯片；开头写 ch。' }, { text: 'school', meaningZh: '学校；ch 不按 chip 的常见模式读。' }],
    '哪个已教的词以 sh 开头，意思是“船”？', '词形：ship', '词形：chip'),
  foundation('同样的 th 不总是同一种声音',
    'thin 的 th 常是 /θ/，this 的 th 常是 /ð/。两者的字形都写 th，音标提醒可能不同；不会音标可先记 thin（薄的）、this（这个）。需要真人参考和实际练习才能核对声音，这里不要求靠读文字分辨清浊。',
    [{ text: 'thin', meaningZh: '薄的；常见 /θ/ 例词。' }, { text: 'this', meaningZh: '这个；常见 /ð/ 例词。' }],
    '按上面说明，哪个词表示“这个”？', '词形：this', '词形：thin'),
  foundation('词尾也看组合：ng、ck',
    'sing 的 ng 通常对应 /ŋ/；back 的 ck 通常对应 /k/，不是两个字母名连念。finger 中 ng 的处理与 sing 不完全相同，规则仍有例外。先认识词形、词义，实际声音留待真人参考核对。',
    [{ text: 'sing', meaningZh: '唱歌；词尾写 ng。' }, { text: 'back', meaningZh: '背部或返回；词尾写 ck。' }, { text: 'finger', meaningZh: '手指；不能只照 sing 猜整词读音。' }],
    '哪组按示范顺序是 ng 结尾、ck 结尾？', '词形：sing / back', '词形：sin / bag'),
  foundation('词里有相对突出的音节',
    '把 table 看成 TA-ble、doctor 看成 DOC-tor：这里的大写只是本站标记常见重音位置，不是另一种拼写。重音与词性、词形有关，不能总猜第一个音节；先看例词标记，是否真的听出或说对还未知。',
    [{ text: 'TA-ble', meaningZh: '桌子；示范把第一部分标为突出。' }, { text: 'DOC-tor', meaningZh: '医生；示范把第一部分标为突出。' }],
    '哪项复现了本站对 table 的重音文字标记？', '标记：TA-ble', '标记：ta-BLE'),
  foundation('按意思读句块，不是逐字念字母',
    'I’m late / because the bus was slow 分成“我迟到了”和“因为公交很慢”两块；斜线是理解辅助，不是强制每次在那里停顿。实际连读和重音要听真人；这里只检查你能否认出写出的意思块。',
    [{ text: "I'm late / because the bus was slow.", meaningZh: '我迟到了 / 因为公交车很慢。' }, { text: 'Can I have / a spoon, please?', meaningZh: '可以给我 / 一把勺子吗？' }],
    '哪项保留了上面“迟到＋原因”的示范句块？', "句块：I'm late / because the bus was slow.", "句块：I'm late / because the spoon was slow."),
  foundation('写短消息：大写 I 与句末标点',
    '英语说“我”时写大写 I；句首通常大写。句号表示陈述，问号表示问题，但标点不能证明实际语调。消息先求意思清楚，不把少一个标点当整体语言能力失败。',
    [{ text: "Hi, I'll be there at six.", meaningZh: '你好，我六点到那里；I 保持大写。' }, { text: 'Are you Jove?', meaningZh: '你是 Jove 吗？句末问号提示问题。' }],
    '哪项保留了示范中的大写 I？', "写法：Hi, I'll be there at six.", "写法：Hi, i'll be there at six."),
  foundation('同样写 oo，也可能不同',
    'room 中 oo 常为 /uː/，book 中 oo 常为 /ʊ/。拼写组合不总对应唯一声音；先把 room（房间）与 book（书）认清，听参考再注意差异，不能从这个文字选择题推定听音或发音掌握。',
    [{ text: 'room', meaningZh: '房间；常见 oo /uː/ 例词。' }, { text: 'book', meaningZh: '书；常见 oo /ʊ/ 例词。' }],
    '哪个已教的词表示“房间”？', '词形：room', '词形：book'),
  foundation('结尾 s 不是每次都一样',
    'files 中 s 常对应 /z/，books 中 s 常对应 /s/，buses 中 es 常多一个 /ɪz/ 音节。这是常见例词提示，仍要结合词和真人声音。这里先看 file/files 的单复数字形，不要求凭文字给录音打分。',
    [{ text: 'file / files', meaningZh: '一份文件 / 多份文件。' }, { text: 'books / buses', meaningZh: '多本书 / 多辆公交车；结尾拼写和常见声音不同。' }],
    '哪个词形明确表示不止一份 file？', '词形：files', '词形：file'),
  foundation('看清数量：-teen 与 -ty',
    'thirteen 表示 13，thirty 表示 30。读音和常见重音可能帮助区分，但强调、语境会改变突出位置，不能只看结尾就认定听得对。先认文字数量，买东西或报时间时可以请对方重复或写下数字。',
    [{ text: 'thirteen / 13', meaningZh: '十三；结尾写 teen。' }, { text: 'thirty / 30', meaningZh: '三十；结尾写 ty。' }],
    '按上面的文字示范，thirty 是哪个数量？', '数量：30', '数量：13'),
  foundation('紧急短句先抓行动与位置',
    'Please call / an ambulance 把“请呼叫”和“救护车”连成有用意思块。不是要求逐字拼字母，也不依据感叹号判断说得多急。真实紧急情况应立即联系当地救援并报位置；本站练习或 AI 消息不是求救渠道。',
    [{ text: 'Please call / an ambulance.', meaningZh: '请呼叫 / 救护车。' }, { text: "I'm at / the station.", meaningZh: '我在 / 车站。' }],
    '哪项写出了示范中的“呼叫救护车”意思块？', '句块：Please call / an ambulance.', '句块：Please call / an apartment.'),
  foundation('回用字母与句块：不是从拼写保证声音',
    'station、six 都以 s 开头，首字母名称仍叫 /ɛs/，在这些词里常是 /s/。把字母名、常见拼读和整句意思分开用；英语有例外。不会写新词时可选已教词块，不凭一次正确选择认定学会整门语言。',
    [{ text: 'station', meaningZh: '车站；在已教消息里使用。' }, { text: 'six', meaningZh: '六；在已教约定时间里使用。' }],
    '哪个已教的词表示“车站”？', '词形：station', '词形：six'),
]

const seeds: Seed[] = [
  { position: 4, titleZh: '报出一个价格', goalZh: '买东西时能听懂或写出一个简单价格，不把数字认错。',
    text: "It's three dollars.", meaningZh: '它是三美元。',
    explanationZh: "It's 是 It is 的缩写，dollars 是美元；three dollars 是三美元，two 是二，five 是五。报价格时 It’s 后面直接接金额，超过一美元通常用 dollars。3 可以写成 three 或数字 3，不要求先背所有数字。",
    pieces: ["It's", 'three', 'dollars.'], recognitionZh: '这句示范报出的价格是多少？', distractorZh: '三十美元',
    expressionZh: '摊位上这件东西标价三美元。告诉买家这个价格，不要变成三十美元。',
    alternatives: ['It is three dollars.', 'Three dollars.', "It's $3."],
    errors: [['It is three dollar.', '价格已接近。超过一美元用 dollars，补上复数即可。'], ["It's thirty dollars.", '这句英语本身成立，但 thirty 是三十；标价是三，用 three，先不要改其他地方。']],
    contexts: [
      ['market', '市集上有人问这本小册子多少钱，标签是三美元。', "It's three dollars.", '它是三美元。', '看清 three，不要因为与参考形式不同就拒绝自然短答。', ['Three dollars.', 'It costs three dollars.']],
      ['ticket', '给朋友发消息说明短途票价是五美元。five（五）已在解释里介绍。', "It's five dollars.", '它是五美元。', '将原金额换成 five，其余结构不必重写；这是简短报价消息。', ['Five dollars.', 'The ticket is five dollars.']],
      ['stall', '朋友问一瓶水的标价，标签是两美元。two 是二。', 'Two dollars.', '两美元。', '面对明确的价格问题，金额短答就够，不用每次写长句。', ["It's two dollars.", 'It costs two dollars.']],
    ] },
  { position: 5, titleZh: '报时间，并约定几点', goalZh: '用小时和分钟说明时间，避免把现在几点和约定几点混在一起。',
    text: "It's nine thirty.", meaningZh: '现在是九点半。', explanationZh: "nine thirty 是 9:30，nine 是九，thirty 是三十分钟。eight o'clock 是八点整。说现在时间可以用 It’s；安排在几点用 at。先读懂这两个具体时间，不要求一次掌握整张时间表。",
    pieces: ["It's", 'nine', 'thirty.'], recognitionZh: '示范中的 nine thirty 表示哪个时间？', distractorZh: '九点十三分', expressionZh: '手机显示 9:30，同伴问现在几点，用已教的短句回答。',
    alternatives: ['It is nine thirty.', "It's 9:30.", 'Nine thirty.'],
    errors: [['It nine thirty.', '报现在时间时，在 It 后补 is；可以直接使用 It’s 这个小块。'], ["It's nine thirteen.", 'thirteen 是十三，thirty 是三十。这次是 9:30，不是 9:13；这是数量区别，不是判断你的口音。']],
    contexts: [
      ['clock', '家里的钟是 9:30，向刚醒来的室友报时间。', "It's nine thirty.", '现在是九点半。', '回答钟表时间，不需要写原因。', ['Nine thirty.', 'It is 9:30.']],
      ['opening', '同事问你说的是几点整，你确认是八点整。', "It's eight o'clock.", '是八点整。', 'o’clock 表示整点；eight 是八，不是今天新的一套问法。', ['Eight o’clock.', "It's 8:00."]],
      ['meeting', '短消息确认见面时间在九点半，不是在报现在几点。', "Let's meet at nine thirty.", '我们九点半见。', 'Let’s meet 是“我们见面吧”，at 后放约定时间。', ["Let's meet at 9:30.", 'We can meet at nine thirty.']],
    ] },
  { position: 6, titleZh: '指出近处或远处的东西', goalZh: '用 this 和 that 指出自己的物品，让对方知道是哪一个。', text: 'This is my bag.', meaningZh: '这是我的包。',
    explanationZh: 'this 指近处这个，that 指远处那个；my 是“我的”，bag 是包，jacket 是外套。This is 后接要介绍的物品；That’s 是 That is 的缩写。先用具体东西练，不要求自己造从未见过的名词。',
    pieces: ['This is', 'my', 'bag.'], recognitionZh: '示范在说近处这个包属于谁？', distractorZh: '这个包属于对方', expressionZh: '你的包就在手边。告诉工作人员“这是我的包”。',
    alternatives: ["This is my bag.", "It's my bag.", 'This bag is mine.'],
    errors: [['This my bag.', '说“这是什么”时，this 后补 is。先用 This is 这个小块。'], ['This is your bag.', 'your 指对方的；你要说自己的包，用 my。句子形式可以成立，但物主与情境不符。']],
    contexts: [
      ['bus', '下车时指着脚边的包，告诉司机这是自己的。', 'This is my bag.', '这是我的包。', 'this 指手边东西，my 指说话者。', ["It's my bag.", 'This bag is mine.']],
      ['coat', '外套挂在远处，你向朋友指出那是自己的外套。', "That's my jacket.", '那是我的外套。', '远处用 that，jacket 的意思已教；不是把 this 永远当唯一答案。', ['That is my jacket.', 'That jacket is mine.']],
      ['photo', '在聊天图片里指着正在圈出的包，简短说明它是你的。', "It's my bag.", '它是我的包。', '对象已明确时，it 可接着指这个包。', ['This is my bag.', 'The bag is mine.']],
    ] },
  { position: 7, titleZh: '介绍朋友和身边的人', goalZh: '让初次见面的人知道你身边的人是谁、与你是什么关系。', text: 'This is my friend.', meaningZh: '这是我的朋友。',
    explanationZh: 'friend 是朋友，colleague 是同事，neighbor 是邻居。This is 可用来介绍身边的人；明确是女性时可用 she，男性可用 he，也可继续用名字或 this person，不必猜性别。关系词不是对方的名字。',
    pieces: ['This is', 'my', 'friend.'], recognitionZh: '示范主要介绍了什么关系？', distractorZh: '对方是你的医生', expressionZh: '你带朋友参加活动，向新认识的人介绍这是你的朋友。',
    alternatives: ['This is a friend of mine.', "They're my friend.", 'This person is my friend.'],
    errors: [['This are my friend.', '这里介绍一个人，This is 才与单数搭配。'], ['This is my friends.', '情境只介绍一位朋友，用 friend；若是几位朋友，需要另外学习复数结构。']],
    contexts: [
      ['party', '聚会时介绍站在身边的一位朋友，不需要报姓名。', 'This is my friend.', '这是我的朋友。', '介绍关系即可，不强迫填私人信息。', ['This is a friend of mine.', 'This person is my friend.']],
      ['office', '向访客介绍身边的一位同事。', 'This is my colleague.', '这是我的同事。', 'colleague 换入同一个介绍结构，避免把工作关系误写成姓名。', ['This person is my colleague.', 'We work together.']],
      ['building', '把身边的一位邻居介绍给刚搬来的朋友。', 'This is my neighbor.', '这是我的邻居。', 'neighbor 是邻居，只换关系词就能完成用途。', ['This person is my neighbor.', 'This is a neighbor of mine.']],
    ] },
  { position: 8, titleZh: '确认物品属于谁', goalZh: '能说明物主，也能礼貌确认是不是对方的东西。', text: 'This key is mine.', meaningZh: '这把钥匙是我的。',
    explanationZh: 'key 是钥匙。my 后面接名词（my key），mine 可单独表示“我的东西”。yours 表示“你的东西”；Is this key yours? 问钥匙是否属于对方。所有权不确定时要问，不要直接声称东西是自己的。',
    pieces: ['This key', 'is', 'mine.'], recognitionZh: '示范中的 mine 表示什么？', distractorZh: '钥匙属于对方', expressionZh: '对方想确认这把钥匙是谁的；你知道它是自己的，用短句说明。',
    alternatives: ["It's my key.", 'This is my key.', 'The key is mine.'],
    errors: [['This key is my.', 'my 后面通常还要名词；这里句末直接用 mine。'], ['This key is yours.', 'yours 是“你的”，情境要说“我的”。不是英语形式错，而是物主反了。']],
    contexts: [
      ['keys', '前台捡到钥匙，你认出是自己的，说明归属。', 'This key is mine.', '这把钥匙是我的。', 'mine 不需要再重复 key。', ['The key is mine.', 'This is my key.']],
      ['bag', '朋友问椅子上那只包属于谁，你知道它是自己的。', 'That bag is mine.', '那个包是我的。', '把 key 换成已学 bag，远处物品用 that。', ["That's my bag.", 'The bag is mine.']],
      ['found', '拾到一把钥匙，问面前的人是否属于他或她，别直接认领。', 'Is this key yours?', '这把钥匙是你的吗？', '疑问句让对方确认；yours 与 mine 的方向不同。', ['Is this your key?', 'Does this key belong to you?']],
    ] },
  { position: 9, titleZh: '说明地点在什么附近', goalZh: '用一个地标说明地点，让朋友知道大致去哪里找。', text: 'The station is near the park.', meaningZh: '车站在公园附近。', sourceUrl: directionsSource,
    explanationZh: 'station 是车站，park 是公园，near 表示附近。next to 表示紧挨着；across the street 表示街对面。bank 是银行，cafe 是咖啡馆，pharmacy 是药店。先用一个明确地标，不要求一次画完整地图。',
    pieces: ['The station', 'is near', 'the park.'], recognitionZh: '这句示范把车站放在什么位置？', distractorZh: '车站离公园很远', expressionZh: '朋友知道公园在哪，问车站在哪。车站就在公园附近，告诉他这个位置。',
    alternatives: ['The station is close to the park.', "It's near the park.", 'The station is by the park.'],
    errors: [['The station near the park.', '说明地点时，在主语后补 is，再接 near。'], ['The station is far from the park.', 'far from 是离得远，句子本身成立；现在要表达附近，用 near。']],
    contexts: [
      ['visitor', '接待朋友时，借已知公园说明车站位置。', 'The station is near the park.', '车站在公园附近。', '用地标缩小寻找范围，near 不保证紧挨着。', ['The station is close to the park.', 'It is near the park.']],
      ['bank', '新同事想找银行，银行紧挨着咖啡馆。', 'The bank is next to the cafe.', '银行紧挨着咖啡馆。', 'next to 比 near 更明确地表示相邻。', ['The bank is beside the cafe.', "It's next to the cafe."]],
      ['pharmacy', '朋友找药店，药店就在你们所在街道的对面。', 'The pharmacy is across the street.', '药店在街对面。', 'across the street 是隔着这条街，不是仅说附近。', ["It's across the street.", 'The pharmacy is on the other side of the street.']],
    ] },
  { position: 10, titleZh: '给一个明确的方向', goalZh: '用转向和地标说清路线中的下一步。', text: 'Turn left at the bank.', meaningZh: '在银行那里左转。', sourceUrl: directionsSource,
    explanationZh: 'turn left 是左转，turn right 是右转；at the bank 指在银行那个地标。go straight 是直走，to the station 是朝车站去。先只给一步，left 和 right 不能互换，未确认的路线不要当真实导航建议。',
    pieces: ['Turn left', 'at', 'the bank.'], recognitionZh: '按示范，到银行后该怎么走？', distractorZh: '在银行那里右转', expressionZh: '练习地图要求到银行左转。给朋友下一步，不要把左右说反。',
    alternatives: ['Take a left at the bank.', 'At the bank, turn left.', 'Make a left at the bank.'],
    errors: [['Turn left the bank.', '转弯地点前补 at，把动作与地标连接起来。'], ['Turn right at the bank.', 'right 是右，情境要求左；句子语法成立，但方向错误，要换成 left。']],
    contexts: [
      ['walk', '练习步行地图要求在银行左转，向同行朋友说下一步。', 'Turn left at the bank.', '在银行那里左转。', '把转向和地标放在同一短句，不要求写三段路线。', ['Take a left at the bank.', 'At the bank, turn left.']],
      ['cafe', '另一张练习地图要求在咖啡馆右转，给朋友留言。', 'Turn right at the cafe.', '在咖啡馆那里右转。', '换地图后不能机械重复 left；right 才符合这次方向。', ['Take a right at the cafe.', 'At the cafe, turn right.']],
      ['station', '在这张练习地图上不必转弯，沿路直走到车站。', 'Go straight to the station.', '直走到车站。', 'go straight 是向前直走，这次不需要 left 或 right。', ['Go straight ahead to the station.', 'Walk straight to the station.']],
    ] },
  { position: 11, titleZh: '礼貌要一件东西', goalZh: '向能提供物品的人提出一个清楚、不过长的请求。', text: 'Can I have a spoon, please?', meaningZh: '可以给我一把勺子吗？', sourceUrl: helpSource,
    explanationZh: 'Can I have 是索取物品的请求小块，a spoon 是一把勺子，please 表示礼貌。fork 是叉子，bag 是包或袋子；Could I have 也可作更委婉请求。给对方物品和向对方要物品方向不同。',
    pieces: ['Can I have', 'a spoon,', 'please?'], recognitionZh: '示范是在向对方要什么？', distractorZh: '递给对方一把勺子', expressionZh: '餐桌上少了一把勺子，向可以拿餐具的服务员礼貌要一把。',
    alternatives: ['Could I have a spoon, please?', 'A spoon, please.', 'Can I get a spoon, please?'],
    errors: [['Can I has a spoon, please?', 'Can 后使用 have，不换成 has；先保留请求小块。'], ['I give you a spoon.', '这句是“我给你勺子”，不是向服务员要勺子。用 Can I have 表达请求。']],
    contexts: [
      ['meal', '吃饭需要勺子，向服务员提出请求。', 'Can I have a spoon, please?', '可以给我一把勺子吗？', '物品与方向清楚即可，不必增加长篇礼貌话。', ['A spoon, please.', 'Could I have a spoon, please?']],
      ['shop', '购物后需要一个袋子，收银员可以给你，礼貌询问。', 'Can I have a bag, please?', '可以给我一个袋子吗？', '同一句型换成 bag，实际费用由店员确认。', ['A bag, please.', 'Could I have a bag, please?']],
      ['fork', '餐盘上只有勺子，你需要叉子，向工作人员请求。', 'Could I have a fork, please?', '可以给我一把叉子吗？', 'fork 是叉子；Could I have 与 Can I have 都是这里合适的请求。', ['Can I have a fork, please?', 'A fork, please.']],
    ] },
  { position: 12, titleZh: '没听明白时请对方再说', goalZh: '不用装懂，可以请求重复、慢一点或确认意思。', text: 'Could you say that again?', meaningZh: '可以再说一遍吗？',
    explanationZh: 'Could you 是向对方提请求，say that again 是把刚才的话再说一次。more slowly 表示慢一点；Do you mean tomorrow? 是确认是否指明天。repeat the address 是重复地址；不把听不懂自动当发音问题。',
    pieces: ['Could you', 'say that', 'again?'], recognitionZh: '示范想让对方做什么？', distractorZh: '让对方不要再说话', expressionZh: '接待人员刚说了一句话，你没听明白。礼貌请对方重复，不要猜一个答案。',
    alternatives: ['Could you repeat that, please?', 'Can you say that again, please?', 'Sorry, could you say that again?'],
    errors: [['Could you said that again?', 'Could 后用 say，不用过去式 said；先修这一个位置。'], ['Could you stop talking?', '这句是在请对方停下；情境要请对方重说，换成 say that again。']],
    contexts: [
      ['desk', '柜台人员解释流程，你没听清第一句，请他重说。', 'Could you say that again?', '可以再说一遍吗？', '请求重复不是失败，也不用随便确认自己听懂了。', ['Could you repeat that, please?', 'Can you say that again?']],
      ['phone', '电话里对方说得太快，你需要他慢一点。', 'Could you speak more slowly?', '可以说得慢一点吗？', '这次请求改变速度，不只是把同样速度的话再听一次。', ['Could you speak a little more slowly, please?', 'Can you speak more slowly?']],
      ['date', '同事提到日期，你不确定是不是明天，直接确认。', 'Do you mean tomorrow?', '你是指明天吗？', '确认一个具体信息，不必在没听懂时回答 yes。', ['Are you saying tomorrow?', 'Tomorrow, is that right?']],
    ] },
  { position: 13, titleZh: '说一个日常习惯', goalZh: '用一个短句说明自己通常怎么上班或开始一天。', text: 'I take the bus every morning.', meaningZh: '我每天早上坐公交车。',
    explanationZh: 'take the bus 是坐公交，every morning 是每天早上；I walk to work 是走路上班，I start work at nine 是九点开始工作。说自己的日常用 I take，不因中文“每天”省略动作词，也不要求写完整一天的日记。',
    pieces: ['I take', 'the bus', 'every morning.'], recognitionZh: '示范说明了什么日常习惯？', distractorZh: '只说昨天坐过一次公交车', expressionZh: '你通常每天早上坐公交车，向同事说明这个习惯，只写一句就够。',
    alternatives: ['I go by bus every morning.', 'Every morning, I take the bus.', 'I ride the bus every morning.'],
    errors: [['I takes the bus every morning.', '说自己 I 时用 take，不加第三人称单数 s。'], ['I took the bus yesterday.', '这句在说昨天一次经历；情境问每天的习惯，回到 every morning 的日常结构。']],
    contexts: [
      ['commute', '新同事问你通常怎么通勤，你每天早上坐公交。', 'I take the bus every morning.', '我每天早上坐公交车。', '说惯常动作，不自动变成一次过去经历。', ['I go by bus every morning.', 'I ride the bus every morning.']],
      ['neighbor', '和邻居聊天，你平常走路去工作地点，说明这一点。', 'I walk to work.', '我走路上班。', 'walk 是走路，to work 说明目的地或用途。', ['I usually walk to work.', 'I go to work on foot.']],
      ['schedule', '给搭档写短消息，说你一般九点开始工作。', 'I start work at nine.', '我九点开始工作。', '复用已教的 at 加时间，不要求新的长日程表。', ['I start at nine.', 'My workday starts at nine.']],
    ] },
  { position: 14, titleZh: '说自己的喜好与不喜欢', goalZh: '让对方知道你的实际偏好，必要时用简短否定。', text: 'I like tea without sugar.', meaningZh: '我喜欢不加糖的茶。',
    explanationZh: 'I like 表示喜欢，tea 是茶，without sugar 是不加糖。I prefer coffee 表示更喜欢咖啡；I don’t like spicy food 表示不喜欢辣的食物。说真实偏好，否定时保留 don’t，不把每个自然替代表达当错误。',
    pieces: ['I like', 'tea', 'without sugar.'], recognitionZh: '按示范，对方应该了解你的哪种偏好？', distractorZh: '喜欢加糖的茶', expressionZh: '朋友在问你喜欢什么样的茶，你喜欢不加糖的茶，用已教短句说明。',
    alternatives: ['I like unsweetened tea.', 'I prefer tea without sugar.', 'I like my tea without sugar.'],
    errors: [['I likes tea without sugar.', 'I 后用 like，不加 s。'], ['I like tea with sugar.', 'with sugar 是加糖，句子本身成立；这次想说不加糖，要用 without sugar。']],
    contexts: [
      ['tea', '朋友为下次聚会询问茶的偏好，你喜欢不加糖。', 'I like tea without sugar.', '我喜欢不加糖的茶。', '这是偏好表达；若要现在点单，可以另用上一课请求句型。', ['I prefer tea without sugar.', 'I like unsweetened tea.']],
      ['coffee', '同事在茶和咖啡之间让你选，你更喜欢咖啡。', 'I prefer coffee.', '我更喜欢咖啡。', 'prefer 说明两者之间的偏好，不需要否定另一种饮料。', ["I'd prefer coffee.", 'I like coffee better.']],
      ['food', '朋友安排聚餐，你不喜欢辣的食物，提前告诉他。', "I don't like spicy food.", '我不喜欢辣的食物。', 'don’t 保留否定，spicy 是辣的；偏好不是医疗过敏诊断。', ['I do not like spicy food.', "I'm not keen on spicy food."]],
    ] },
  { position: 15, titleZh: '说近期计划', goalZh: '说清将来的安排，而不是把它写成每天的习惯。', text: "I'm meeting a friend tomorrow.", meaningZh: '我明天要见一个朋友。',
    explanationZh: 'I’m meeting 在带 tomorrow 的场景里可以说已安排的见面，不只指此刻正在发生。tomorrow 是明天，tonight 是今晚；I’m going to study tonight 是今晚打算学习。I can meet you at six 是可以六点见你。先用这些具体时间短句，不要求同时背完将来时规则。',
    pieces: ["I'm meeting", 'a friend', 'tomorrow.'], recognitionZh: '示范的见面发生在什么时候？', distractorZh: '昨天', expressionZh: '你已和朋友约好明天见面，告诉同事这个近期安排。',
    alternatives: ['I am meeting a friend tomorrow.', "I'll meet a friend tomorrow.", "I'm going to meet a friend tomorrow."],
    errors: [['I meeting a friend tomorrow.', 'meeting 前需要 am；可以直接用 I’m meeting。'], ["I'm meeting a friend yesterday.", 'yesterday 是昨天，与这里的未来安排不一致；保留明天的 tomorrow。']],
    contexts: [
      ['friend', '向室友说明自己明天约好了见一位朋友。', "I'm meeting a friend tomorrow.", '我明天要见一个朋友。', '用明确日期的小块帮助对方理解安排。', ['I am meeting a friend tomorrow.', "I'm going to meet a friend tomorrow."]],
      ['study', '给朋友发消息说你今晚打算学习，不能去聚会。只需说计划。', "I'm going to study tonight.", '我今晚打算学习。', 'going to 加 study 说明计划，tonight 是今晚。', ['I plan to study tonight.', "I'll study tonight."]],
      ['six', '对方在问见面的可用时间，你可以六点见他。', 'I can meet you at six.', '我可以六点见你。', 'can 说明可行性，at six 是时间；不要照抄 tomorrow 丢失具体时间。', ["I'm free to meet at six.", 'Six works for me.']],
    ] },
  { position: 16, titleZh: '说一次已经发生的经历', goalZh: '用昨天或刚才的线索说明过去发生的事，不编造完整故事。', text: 'I went to the store yesterday.', meaningZh: '我昨天去了商店。',
    explanationZh: 'went 是 go 的常见过去式，yesterday 是昨天；不能同时写 did went。I was at home yesterday 表示昨天在家；I bought some milk 表示买了一些牛奶；I missed the bus this morning 表示今天早上没赶上公交。先学少量高用处过去词块，没教的新经历可先用中文求助。',
    pieces: ['I went', 'to the store', 'yesterday.'], recognitionZh: '示范在说哪一次经历？', distractorZh: '明天打算去商店', expressionZh: '同伴问昨天做了什么，你昨天去了商店，用一句已教短句说明。',
    alternatives: ['Yesterday, I went to the store.', 'I visited the store yesterday.', 'I went to a store yesterday.'],
    errors: [['I goed to the store yesterday.', 'go 的这个常见过去式是 went，不机械加 ed。'], ['I did went to the store yesterday.', 'did 后应回到 go；最简单先使用整块 I went，别同时放 did 和 went。']],
    contexts: [
      ['errand', '朋友问昨天去过哪里，你去了商店。', 'I went to the store yesterday.', '我昨天去了商店。', '复用 went 和 yesterday，不需要详细购物记录。', ['Yesterday, I went to the store.', 'I went to a store yesterday.']],
      ['home', '同事以为昨天在公园见过你，你说明昨天在家。', 'I was at home yesterday.', '我昨天在家。', 'was 是这里 I am 的过去形式，地点换成 home。', ['Yesterday, I was at home.', 'I stayed home yesterday.']],
      ['bus', '早上没赶上公交，给同伴解释刚才发生的事。', 'I missed the bus this morning.', '我今天早上没赶上公交车。', 'missed the bus 是未赶上公交，不是想念这辆车；this morning 指今天早上。', ['I did not catch the bus this morning.', "I didn't catch the bus this morning."]],
    ] },
  { position: 17, titleZh: '给一个温和的看法', goalZh: '用 I think 给出具体看法，不把意见写成确定事实。', text: 'I think this is a good idea.', meaningZh: '我觉得这是一个好主意。',
    explanationZh: 'I think 表示“我觉得”，后面接看法；a good idea 是一个好主意。we need more time 是我们需要更多时间，this room is too small 是房间太小，this route is easier 是这条路线更容易。看法可以不同，今天只练如何说明，不因为意见不同给人打能力分。',
    pieces: ['I think', 'this is', 'a good idea.'], recognitionZh: '示范是在怎样回应这个主意？', distractorZh: '明确反对这个主意', expressionZh: '同伴提出一个主意，你想表示赞同，觉得它是好主意。用已教短句说明。',
    alternatives: ["I think it's a good idea.", 'That sounds like a good idea.', 'I think this idea is good.'],
    errors: [['I think this a good idea.', 'think 后面的看法还需要 is：this is a good idea。'], ['I think this is a bad idea.', '这句是自然英语，但表达反对；本情境要赞同，所以把 bad 换成 good。不是禁止你有不同看法。']],
    contexts: [
      ['team', '团队讨论结束时间，你觉得还需要更多时间，礼貌提出看法。', 'I think we need more time.', '我觉得我们需要更多时间。', '用 I think 表明是自己的判断，不只重复“好主意”。', ['We may need more time.', 'I think we need a little more time.']],
      ['room', '看房后你觉得房间太小，向朋友说自己的看法。', 'I think this room is too small.', '我觉得这个房间太小。', 'too small 是对当前需要而言太小，不是声称所有人都不能住。', ["I think it's too small.", 'This room seems too small to me.']],
      ['route', '两条练习路线中，你觉得这条更容易，提出自己的判断。', 'I think this route is easier.', '我觉得这条路线更容易。', 'easier 是更容易，this route 是这条路线；不是未经确认的真实导航保证。', ['This route seems easier to me.', 'I think this is the easier route.']],
    ] },
  { position: 18, titleZh: '用 because 给一个原因', goalZh: '把一件事和一个简短原因连起来，而不是罗列零散词。', text: "I'm late because the bus was slow.", meaningZh: '我迟到了，因为公交车很慢。',
    explanationZh: 'because 连接原因；I’m late 说明迟到，the bus was slow 说明原因。I can’t come because I’m ill 是因病不能来；I need help because this is new 是事情陌生所以需要帮助。原因只说自己知道的事实，不需要填长篇感想。',
    pieces: ["I'm late", 'because', 'the bus was slow.'], recognitionZh: '按示范，迟到的原因是什么？', distractorZh: '因为不喜欢同伴', expressionZh: '在练习场景中你迟到了，已知公交很慢。给同伴一条说明事实的消息。',
    alternatives: ['I am late because the bus was slow.', 'The bus was slow, so I am late.', "I'm late because of the slow bus."],
    errors: [["I'm late because the bus slow.", '原因里的公交情况也要有 was：the bus was slow；不必改动整条消息。'], ["I'm late because I don't like you.", '这句表达了另一种原因；练习中已知的是公交慢，不要凭空换成不喜欢对方。']],
    contexts: [
      ['late', '给等候的朋友说明练习里公交慢造成的迟到。', "I'm late because the bus was slow.", '我迟到了，因为公交车很慢。', '先说明发生什么，再用 because 说明一个真实已知原因。', ['I am late because the bus was slow.', 'The bus was slow, so I am late.']],
      ['ill', '练习里你生病了，写一条短消息说明不能参加聚会。', "I can't come because I'm ill.", '我不能来，因为我生病了。', 'can’t come 表示不能参加，ill 是生病；这里练表达，不提供疾病判断。', ['I cannot come because I am ill.', "I'm ill, so I can't come."]],
      ['new', '你第一次操作某个流程，向同事说明为什么需要帮助。', 'I need help because this is new.', '我需要帮助，因为这件事是新的。', '复用 I need，再给原因；不知道的细节可以继续问。', ['This is new to me, so I need help.', 'I need help because this is new to me.']],
    ] },
  { position: 19, titleZh: '写一条清楚的短消息', goalZh: '用问候、一个关键信息和简短收尾完成实际消息，不写无目的作文。', text: "Hi, I'll be there at six.", meaningZh: '你好，我六点到那里。',
    explanationZh: 'Hi 是问候，I’ll 是 I will 的缩写，be there at six 是六点到那里。I’m on my way 是我正在路上；I’ll be ten minutes late 是我要晚十分钟；Thanks. See you at six 是谢谢，六点见。一条消息说明一个事实就足够，不强迫添长段落。',
    pieces: ['Hi,', "I'll be there", 'at six.'], recognitionZh: '示范告诉收件人的关键信息是什么？', distractorZh: '六点时已经离开那里', expressionZh: '你向熟悉地点的朋友确认自己六点到那里。写一条短消息，不需要地址或私人资料。',
    alternatives: ['Hi, I will be there at six.', "Hello, I'll be there at six.", "I'll be there at 6."],
    errors: [['Hi, I will there at six.', 'will 后还需要 be；先用 I’ll be there 这个小块。'], ["Hi, I'll leave there at six.", '这句是六点离开，与你要说明六点到那里的用途不同；用 be there。']],
    contexts: [
      ['arrival', '朋友已知道约定地点，你告知正在路上，不必再写整份行程。', "Hi, I'm on my way.", '你好，我正在路上。', 'on my way 是一个整体，说明正朝目的地去。', ["I'm on my way.", 'Hello, I am on my way.']],
      ['delay', '练习中会比约定时间晚十分钟，给等候的人发一条消息。', "Sorry, I'll be ten minutes late.", '抱歉，我会晚十分钟。', 'ten minutes late 说明延误长度；不用编造原因。', ['Sorry, I will be ten minutes late.', "I'll be ten minutes late. Sorry."]],
      ['confirm', '对方确认六点见面，你回复感谢并简短收尾。', 'Thanks. See you at six.', '谢谢，六点见。', '收尾不必重新写一段自我介绍；两小句足够。', ['Thank you. See you at six.', 'Thanks, see you at 6.']],
    ] },
  { position: 20, titleZh: '向房东报告一个住房问题', goalZh: '明确说出哪件设施出了问题，再请求处理，不填写整篇投诉。', text: "The hot water isn't working.", meaningZh: '热水设施不能正常使用。', sourceUrl: helpSource,
    explanationZh: 'hot water 是热水，isn’t working 表示不能正常使用，不是说“没上班”。heater 是暖气；a leak under the sink 是水槽下面漏水。Could you check the hot water? 请求检查热水，不等于已经判断故障原因。这里只练报告，不提供维修或安全操作指令。',
    pieces: ['The hot water', "isn't", 'working.'], recognitionZh: '示范报告的是哪个问题？', distractorZh: '热水设施一切正常', expressionZh: '练习租住的房子不能正常供应热水，向房东报告这一个问题。',
    alternatives: ['The hot water is not working.', "The hot water doesn't work.", 'I have no hot water.'],
    errors: [['The hot water not working.', '在 not 前补 is；可以用 isn’t working 小块。'], ['The hot water is working.', '这句说设施正常；你要报告故障，保留 isn’t 或 is not 的否定。']],
    contexts: [
      ['water', '向房东写消息说明热水不能正常使用，不猜故障原因。', "The hot water isn't working.", '热水设施不能正常使用。', '指出问题即可，真实处理需由合适人员检查。', ['The hot water is not working.', 'I have no hot water.']],
      ['heater', '练习房间的暖气不工作，向管理人员报告。', "The heater isn't working.", '暖气不能正常使用。', 'heater 换入同一结构，不要把它说成热水。', ['The heater is not working.', "The heater doesn't work."]],
      ['leak', '练习里看到水槽下面在漏水，说明你观察到的位置。', "There's a leak under the sink.", '水槽下面有漏水。', 'There’s 表示有，under the sink 说明在水槽下面；不推测未观察到的原因。', ['There is a leak under the sink.', 'Water is leaking under the sink.']],
    ] },
  { position: 21, titleZh: '工作中请求核对并说明截止时间', goalZh: '用简短请求或时间说明与同事协作，不装懂没明白的任务。', text: 'Could you check this file, please?', meaningZh: '可以帮忙检查这份文件吗？', sourceUrl: helpSource,
    explanationZh: 'check this file 是检查这份文件；Could you 把动作请求交给对方。I’ll send the file by five 表示五点之前发送，by 是最晚期限，不必正好五点。When is this due? 问何时截止。I need help with this task 表示这个任务需要帮助，不要求填写工作隐私。',
    pieces: ['Could you', 'check this file,', 'please?'], recognitionZh: '示范希望同事帮忙做什么？', distractorZh: '删除这份文件', expressionZh: '在练习工作场景里，你想请同事检查文件，明确提出这个请求。',
    alternatives: ['Can you check this file, please?', 'Could you review this file, please?', 'Please check this file.'],
    errors: [['Could you checks this file, please?', 'Could you 后用 check，不加 s。'], ['Could you delete this file, please?', 'delete 是删除，句子本身成立；你的用途是核对，要使用 check。']],
    contexts: [
      ['review', '同事愿意帮忙，你请他核对练习文件，不让他删除。', 'Could you check this file, please?', '可以帮忙检查这份文件吗？', '只提出一件清楚的事，避免把陌生专业词塞进请求。', ['Can you check this file, please?', 'Please check this file.']],
      ['deadline', '练习任务要求最晚五点提交，你向搭档说明会在期限前发送。', "I'll send the file by five.", '我会在五点之前发送文件。', 'by five 是最晚五点，不等于只在五点那一刻发送。', ['I will send the file by five.', "I'll send it by five."]],
      ['due', '新任务的截止时间没说清楚，你向同事确认。', 'When is this due?', '这个什么时候截止？', 'due 用于这里的到期或截止，不需要猜一个日期。', ['When is the deadline?', 'What is the deadline for this?']],
    ] },
  { position: 22, titleZh: '简单说明身体不适', goalZh: '在练习中表达一个症状或已知过敏信息，不用语言练习替代医疗判断。', text: 'I have a headache.', meaningZh: '我头疼。',
    explanationZh: 'have a headache 表示头疼，不是“我是头疼”。My stomach hurts 表示胃部或腹部疼；I’m allergic to peanuts 表示已知对花生过敏；I need a doctor 是需要医生。这些是表达例句，不是让网站诊断病情、判断急不急或推荐药物。',
    pieces: ['I have', 'a', 'headache.'], recognitionZh: '示范中说话者表达什么不适？', distractorZh: '没有任何不适', expressionZh: '练习中你向接待人员说明头疼，用一个已教短句；不填真实病历。',
    alternatives: ['My head hurts.', "I've got a headache.", 'I have a pain in my head.'],
    errors: [['I am a headache.', '这是把自己说成“一个头疼”；说明有症状用 I have a headache。'], ['I has a headache.', 'I 后用 have，不用 has。这里只修语言，不判定症状真假。']],
    contexts: [
      ['desk', '在模拟诊所向接待人员简短说明头疼，不请求网站诊断。', 'I have a headache.', '我头疼。', '清楚表达一个症状，是否需要处理由实际医疗人员判断。', ['My head hurts.', "I've got a headache."]],
      ['stomach', '模拟就诊里，你需要说胃部或腹部疼，不能照抄头疼。', 'My stomach hurts.', '我胃部或腹部疼。', 'stomach 是这里腹部的日常说法，不据此推断具体器官或病因。', ['I have a stomachache.', 'I have a pain in my stomach.']],
      ['allergy', '练习设定中你已有明确花生过敏史，告诉餐厅工作人员。', "I'm allergic to peanuts.", '我对花生过敏。', 'allergic to 说明已知过敏，不是表示不喜欢；真实饮食安全不能依赖本练习。', ['I am allergic to peanuts.', 'I have a peanut allergy.']],
    ] },
  { position: 23, titleZh: '紧急情况说行动和位置', goalZh: '在模拟求助里说清需要何种帮助，并能提供位置。', text: 'Please call an ambulance.', meaningZh: '请叫救护车。', sourceUrl: helpSource,
    explanationZh: 'call an ambulance 是呼叫救护车，不是公寓 apartment。fire department 是消防部门；I’m at the station 是我在车站；Someone is hurt 是有人受伤。真实紧急情况请立即联系当地救援并报位置，不要等网站或 AI；这里不规定各地号码，也不是求救渠道。',
    pieces: ['Please call', 'an', 'ambulance.'], recognitionZh: '示范希望对方采取什么行动？', distractorZh: '联系公寓看房', expressionZh: '只在模拟场景里，你需要让身边的人呼叫救护车。用已教的行动短句，不上传真实求救信息。',
    alternatives: ['Call an ambulance, please.', 'Could you call an ambulance?', 'Please call for an ambulance.'],
    errors: [['Please call a ambulance.', 'ambulance 前通常用 an，先修冠词即可。'], ['Please call an apartment.', 'apartment 是公寓，ambulance 才是救护车。这里是物品词混淆，不是对发音作诊断。']],
    contexts: [
      ['ambulance', '在角色练习里，向身边的人明确请求呼叫救护车。', 'Please call an ambulance.', '请叫救护车。', '简短行动句优先；真实紧急情况不要等待本站反馈。', ['Call an ambulance, please.', 'Could you call an ambulance?']],
      ['fire', '在模拟消防求助中，需要向身边的人说应联系消防部门。', 'Call the fire department, please.', '请联系消防部门。', 'fire department 换成正确帮助对象；本句不提供处理火灾的操作指令。', ['Please call the fire department.', 'Could you call the fire department?']],
      ['location', '模拟电话里对方问你在哪里，你在车站，直接报位置。', "I'm at the station.", '我在车站。', '位置问题回答位置，不继续重复请求；真实求助还需按当地接线员要求补充信息。', ['I am at the station.', 'My location is the station.']],
    ] },
  { position: 24, titleZh: '把地点和时间写进约定', goalZh: '把已学问候、时间、地点与澄清组合成一条有用途的短消息。', text: 'Hi, can we meet at the station?', meaningZh: '你好，我们可以在车站见面吗？',
    explanationZh: 'Can we meet 是商量见面，at the station 是地点。Can we meet at six? 商量六点；Can we meet tomorrow? 商量明天。I’m at the station. Where are you? 先报位置再问对方在哪里。只用本课已经展示的词块组合，可请求帮助，不强制写未教的自由作文；24 课完成也不代表流利或达到某个等级。',
    pieces: ['Hi,', 'can we meet', 'at the station?'], recognitionZh: '示范是在商量哪件事？', distractorZh: '已经确定再也不见面', expressionZh: '你想与朋友商量在车站见面，用一条已教短消息提出建议，别假定对方已经同意。',
    alternatives: ['Can we meet at the station?', 'Hello, can we meet at the station?', 'Could we meet at the station?'],
    errors: [['Hi, can we meets at the station?', 'can 后用 meet，不加 s；保留地点信息。'], ['Hi, can we meet on the station?', '这里表示在车站这个地点，用 at the station；on 不是本情境的搭配。']],
    contexts: [
      ['time', '对方已知道地点，你只想商量六点见面，发一条简短消息。', 'Hi, can we meet at six?', '你好，我们可以六点见面吗？', '地点已经共同知道时，只补时间就够，不必抄回整句地点。', ['Can we meet at six?', 'Could we meet at six?']],
      ['reschedule', '今天不方便，你礼貌提出改到明天，还需要对方确认。', 'Sorry, can we meet tomorrow?', '抱歉，我们可以明天见面吗？', '用明天的 tomorrow 提议，Sorry 简短致意，不把提议当已确认安排。', ['Could we meet tomorrow?', 'Can we meet tomorrow instead?']],
      ['find', '约好后你已到车站，发消息先说明自己位置，再问朋友在哪里。', "I'm at the station. Where are you?", '我在车站。你在哪里？', '两小句分别完成报位置和问位置，不要求追加长篇日记。', ['I am at the station. Where are you?', "I'm at the station. Where are you now?"]],
    ] },
]

function build(seed: Seed): StarterLesson {
  const id = `en-starter-${seed.position}`
  const variants = seed.contexts.map(([key, promptZh, reference, meaningZh, explanationZh, alternatives]) => ({
    id: `${id}-${key}`, promptZh: `${promptZh} 需要时可先看本情境示范句块。`,
    reference, accepted: [reference, ...alternatives], meaningZh, explanationZh,
  }))
  const choices = [{ id: 'purpose', textZh: seed.meaningZh }, { id: 'contrast', textZh: seed.distractorZh }]
  return { id, language: 'en', version: 1, position: seed.position, titleZh: seed.titleZh, goalZh: seed.goalZh,
    prerequisites: [`en-starter-${seed.position - 1}`], minutes: { quick: 5, standard: 10 },
    model: { text: seed.text, meaningZh: seed.meaningZh,
      explanationZh: `${seed.explanationZh} 换场景可先用：${variants.map(item => `${item.reference}（${item.meaningZh}）`).join('；')}` },
    recognition: { promptZh: seed.recognitionZh, choices: seed.position % 2 ? [...choices].reverse() : choices,
      answerId: 'purpose', explanationZh: `示范“${seed.text}”表达的是“${seed.meaningZh}”，不是“${seed.distractorZh}”。` },
    scaffold: { promptZh: `先看过示范，再点词块表达“${seed.meaningZh}”，不用自己拼新词。`, pieces: seed.pieces,
      answer: seed.text, explanationZh: `把已教词块连成 ${seed.text}（${seed.meaningZh}）。用提示练成不等于独立掌握。` },
    expression: { promptZh: `${seed.expressionZh} 需要时可看示范词块再试。`,
      reference: seed.text, accepted: [...new Set([seed.text, ...seed.alternatives])],
      errors: seed.errors.map(([input, feedbackZh]) => ({ input, feedbackZh, corrected: seed.text })) },
    transfer: variants,
    sound: { sourceLabel: '本站原创教学句（非原站字幕）＋ VOA 官方真人参考链接', sourceUrl: seed.sourceUrl ?? alphabetSource,
      status: 'pending-review', notesZh: '本课没有已独立试听核对的逐句真人或合成示范音频，也没有新本地音频文件。原站只作真人英语参考，本站原创句不保证逐字出现在原站。听不到时仍可做文字与字形练习，听力、口音和发音掌握仍未知；待人工审校，不作流利或等级保证。' },
    foundation: foundations[seed.position - 4]!,
  }
}

function freeze<T>(value: T): T {
  if (value && typeof value === 'object') { for (const child of Object.values(value)) freeze(child); Object.freeze(value) }
  return value
}

/** Original continuation only; the preserved three entry lessons live elsewhere.
 * Editorial sequencing is not a CEFR placement or a human efficacy result. */
export const englishContinuingLessons: readonly StarterLesson[] = freeze(seeds.map(build))
